// Code generated by protoc-gen-go. DO NOT EDIT.
// source: study-service-api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Study struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Study) Reset()         { *m = Study{} }
func (m *Study) String() string { return proto.CompactTextString(m) }
func (*Study) ProtoMessage()    {}
func (*Study) Descriptor() ([]byte, []int) {
	return fileDescriptor_81f0d8f98f9be15c, []int{0}
}

func (m *Study) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Study.Unmarshal(m, b)
}
func (m *Study) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Study.Marshal(b, m, deterministic)
}
func (m *Study) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Study.Merge(m, src)
}
func (m *Study) XXX_Size() int {
	return xxx_messageInfo_Study.Size(m)
}
func (m *Study) XXX_DiscardUnknown() {
	xxx_messageInfo_Study.DiscardUnknown(m)
}

var xxx_messageInfo_Study proto.InternalMessageInfo

type Question struct {
	Items                []*any.Any `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Question) Reset()         { *m = Question{} }
func (m *Question) String() string { return proto.CompactTextString(m) }
func (*Question) ProtoMessage()    {}
func (*Question) Descriptor() ([]byte, []int) {
	return fileDescriptor_81f0d8f98f9be15c, []int{1}
}

func (m *Question) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Question.Unmarshal(m, b)
}
func (m *Question) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Question.Marshal(b, m, deterministic)
}
func (m *Question) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Question.Merge(m, src)
}
func (m *Question) XXX_Size() int {
	return xxx_messageInfo_Question.Size(m)
}
func (m *Question) XXX_DiscardUnknown() {
	xxx_messageInfo_Question.DiscardUnknown(m)
}

var xxx_messageInfo_Question proto.InternalMessageInfo

func (m *Question) GetItems() []*any.Any {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*Study)(nil), "influenzanet.study_service_api.Study")
	proto.RegisterType((*Question)(nil), "influenzanet.study_service_api.Question")
}

func init() { proto.RegisterFile("study-service-api.proto", fileDescriptor_81f0d8f98f9be15c) }

var fileDescriptor_81f0d8f98f9be15c = []byte{
	// 248 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x8f, 0x4d, 0x4b, 0x03, 0x31,
	0x10, 0x86, 0xd1, 0xb2, 0x55, 0x62, 0x41, 0x08, 0xc5, 0x8f, 0x15, 0x54, 0x7a, 0x12, 0x61, 0x53,
	0xa8, 0xd0, 0x7b, 0x15, 0x0f, 0xde, 0xd4, 0xbd, 0x79, 0x29, 0xb3, 0x3a, 0x5d, 0x06, 0x76, 0x93,
	0xb0, 0x99, 0x14, 0xd6, 0xbf, 0xe2, 0x9f, 0x95, 0x26, 0xe9, 0xa1, 0x7a, 0xe8, 0x71, 0x78, 0x9f,
	0x67, 0x66, 0x5e, 0x71, 0xee, 0xd8, 0x7f, 0xf5, 0x85, 0xc3, 0x6e, 0x4d, 0x9f, 0x58, 0x80, 0x25,
	0x65, 0x3b, 0xc3, 0x46, 0x5e, 0x93, 0x5e, 0x35, 0x1e, 0xf5, 0x37, 0x68, 0x64, 0x15, 0xa8, 0x65,
	0xa2, 0x96, 0x60, 0x29, 0x97, 0x75, 0x63, 0x2a, 0x68, 0x0a, 0xee, 0x2d, 0xba, 0xe8, 0xe4, 0x23,
	0xe7, 0xbb, 0x35, 0xf6, 0x69, 0xba, 0xaa, 0x8d, 0xa9, 0x1b, 0x9c, 0x86, 0xa9, 0xf2, 0xab, 0x29,
	0xb6, 0x96, 0xb7, 0xe1, 0xe5, 0xdf, 0x10, 0x74, 0x8a, 0x26, 0x47, 0x22, 0x2b, 0x37, 0xe7, 0x26,
	0x73, 0x71, 0xfc, 0xe6, 0xd1, 0x31, 0x19, 0x2d, 0xef, 0x45, 0x46, 0x8c, 0xad, 0xbb, 0x38, 0xbc,
	0x1d, 0xdc, 0x9d, 0xcc, 0xc6, 0x2a, 0xfa, 0x6a, 0xeb, 0xab, 0x85, 0xee, 0xdf, 0x23, 0x32, 0xfb,
	0x39, 0x10, 0xa7, 0x61, 0x43, 0x19, 0xff, 0x5d, 0x58, 0x92, 0x73, 0x31, 0x2c, 0x19, 0xd8, 0x3b,
	0x79, 0xf6, 0x4f, 0x7d, 0xde, 0xfc, 0x95, 0x8f, 0xd5, 0x4e, 0xe3, 0x44, 0xbf, 0x8a, 0xd1, 0x53,
	0x87, 0xc0, 0x58, 0x86, 0x6a, 0xf2, 0x66, 0x97, 0x4a, 0x85, 0x63, 0xf8, 0xc2, 0xd8, 0xe6, 0xfb,
	0x80, 0xc7, 0xec, 0x63, 0x00, 0x96, 0xaa, 0x61, 0x38, 0xff, 0xf0, 0x1b, 0x00, 0x00, 0xff, 0xff,
	0x8e, 0xb3, 0xdd, 0xef, 0x81, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StudyServiceApiClient is the client API for StudyServiceApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StudyServiceApiClient interface {
	Status(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Status, error)
	CreateSurvey(ctx context.Context, in *SurveyItem, opts ...grpc.CallOption) (*SurveyItem, error)
}

type studyServiceApiClient struct {
	cc *grpc.ClientConn
}

func NewStudyServiceApiClient(cc *grpc.ClientConn) StudyServiceApiClient {
	return &studyServiceApiClient{cc}
}

func (c *studyServiceApiClient) Status(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/influenzanet.study_service_api.StudyServiceApi/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studyServiceApiClient) CreateSurvey(ctx context.Context, in *SurveyItem, opts ...grpc.CallOption) (*SurveyItem, error) {
	out := new(SurveyItem)
	err := c.cc.Invoke(ctx, "/influenzanet.study_service_api.StudyServiceApi/CreateSurvey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StudyServiceApiServer is the server API for StudyServiceApi service.
type StudyServiceApiServer interface {
	Status(context.Context, *empty.Empty) (*Status, error)
	CreateSurvey(context.Context, *SurveyItem) (*SurveyItem, error)
}

// UnimplementedStudyServiceApiServer can be embedded to have forward compatible implementations.
type UnimplementedStudyServiceApiServer struct {
}

func (*UnimplementedStudyServiceApiServer) Status(ctx context.Context, req *empty.Empty) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (*UnimplementedStudyServiceApiServer) CreateSurvey(ctx context.Context, req *SurveyItem) (*SurveyItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSurvey not implemented")
}

func RegisterStudyServiceApiServer(s *grpc.Server, srv StudyServiceApiServer) {
	s.RegisterService(&_StudyServiceApi_serviceDesc, srv)
}

func _StudyServiceApi_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyServiceApiServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/influenzanet.study_service_api.StudyServiceApi/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyServiceApiServer).Status(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudyServiceApi_CreateSurvey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SurveyItem)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyServiceApiServer).CreateSurvey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/influenzanet.study_service_api.StudyServiceApi/CreateSurvey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyServiceApiServer).CreateSurvey(ctx, req.(*SurveyItem))
	}
	return interceptor(ctx, in, info, handler)
}

var _StudyServiceApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "influenzanet.study_service_api.StudyServiceApi",
	HandlerType: (*StudyServiceApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _StudyServiceApi_Status_Handler,
		},
		{
			MethodName: "CreateSurvey",
			Handler:    _StudyServiceApi_CreateSurvey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "study-service-api.proto",
}
