// Code generated by protoc-gen-go. DO NOT EDIT.
// source: study.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Study struct {
	Id                   string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StudyKey             string         `protobuf:"bytes,2,opt,name=study_key,json=studyKey,proto3" json:"study_key,omitempty"`
	Props                *Study_Props   `protobuf:"bytes,3,opt,name=props,proto3" json:"props,omitempty"`
	Configs              *Study_Configs `protobuf:"bytes,4,opt,name=configs,proto3" json:"configs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Study) Reset()         { *m = Study{} }
func (m *Study) String() string { return proto.CompactTextString(m) }
func (*Study) ProtoMessage()    {}
func (*Study) Descriptor() ([]byte, []int) {
	return fileDescriptor_b59e246e4c4c09f0, []int{0}
}

func (m *Study) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Study.Unmarshal(m, b)
}
func (m *Study) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Study.Marshal(b, m, deterministic)
}
func (m *Study) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Study.Merge(m, src)
}
func (m *Study) XXX_Size() int {
	return xxx_messageInfo_Study.Size(m)
}
func (m *Study) XXX_DiscardUnknown() {
	xxx_messageInfo_Study.DiscardUnknown(m)
}

var xxx_messageInfo_Study proto.InternalMessageInfo

func (m *Study) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Study) GetStudyKey() string {
	if m != nil {
		return m.StudyKey
	}
	return ""
}

func (m *Study) GetProps() *Study_Props {
	if m != nil {
		return m.Props
	}
	return nil
}

func (m *Study) GetConfigs() *Study_Configs {
	if m != nil {
		return m.Configs
	}
	return nil
}

type Study_Props struct {
	StudyName            string   `protobuf:"bytes,3,opt,name=study_name,json=studyName,proto3" json:"study_name,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Study_Props) Reset()         { *m = Study_Props{} }
func (m *Study_Props) String() string { return proto.CompactTextString(m) }
func (*Study_Props) ProtoMessage()    {}
func (*Study_Props) Descriptor() ([]byte, []int) {
	return fileDescriptor_b59e246e4c4c09f0, []int{0, 0}
}

func (m *Study_Props) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Study_Props.Unmarshal(m, b)
}
func (m *Study_Props) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Study_Props.Marshal(b, m, deterministic)
}
func (m *Study_Props) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Study_Props.Merge(m, src)
}
func (m *Study_Props) XXX_Size() int {
	return xxx_messageInfo_Study_Props.Size(m)
}
func (m *Study_Props) XXX_DiscardUnknown() {
	xxx_messageInfo_Study_Props.DiscardUnknown(m)
}

var xxx_messageInfo_Study_Props proto.InternalMessageInfo

func (m *Study_Props) GetStudyName() string {
	if m != nil {
		return m.StudyName
	}
	return ""
}

func (m *Study_Props) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Study_Configs struct {
	Rules                []*Expression `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Study_Configs) Reset()         { *m = Study_Configs{} }
func (m *Study_Configs) String() string { return proto.CompactTextString(m) }
func (*Study_Configs) ProtoMessage()    {}
func (*Study_Configs) Descriptor() ([]byte, []int) {
	return fileDescriptor_b59e246e4c4c09f0, []int{0, 1}
}

func (m *Study_Configs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Study_Configs.Unmarshal(m, b)
}
func (m *Study_Configs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Study_Configs.Marshal(b, m, deterministic)
}
func (m *Study_Configs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Study_Configs.Merge(m, src)
}
func (m *Study_Configs) XXX_Size() int {
	return xxx_messageInfo_Study_Configs.Size(m)
}
func (m *Study_Configs) XXX_DiscardUnknown() {
	xxx_messageInfo_Study_Configs.DiscardUnknown(m)
}

var xxx_messageInfo_Study_Configs proto.InternalMessageInfo

func (m *Study_Configs) GetRules() []*Expression {
	if m != nil {
		return m.Rules
	}
	return nil
}

type AssignedSurvey struct {
	SurveyKey            string   `protobuf:"bytes,1,opt,name=survey_key,json=surveyKey,proto3" json:"survey_key,omitempty"`
	ValidFrom            int64    `protobuf:"varint,2,opt,name=valid_from,json=validFrom,proto3" json:"valid_from,omitempty"`
	ValidUntil           int64    `protobuf:"varint,3,opt,name=valid_until,json=validUntil,proto3" json:"valid_until,omitempty"`
	StudyKey             string   `protobuf:"bytes,4,opt,name=study_key,json=studyKey,proto3" json:"study_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AssignedSurvey) Reset()         { *m = AssignedSurvey{} }
func (m *AssignedSurvey) String() string { return proto.CompactTextString(m) }
func (*AssignedSurvey) ProtoMessage()    {}
func (*AssignedSurvey) Descriptor() ([]byte, []int) {
	return fileDescriptor_b59e246e4c4c09f0, []int{1}
}

func (m *AssignedSurvey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssignedSurvey.Unmarshal(m, b)
}
func (m *AssignedSurvey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssignedSurvey.Marshal(b, m, deterministic)
}
func (m *AssignedSurvey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssignedSurvey.Merge(m, src)
}
func (m *AssignedSurvey) XXX_Size() int {
	return xxx_messageInfo_AssignedSurvey.Size(m)
}
func (m *AssignedSurvey) XXX_DiscardUnknown() {
	xxx_messageInfo_AssignedSurvey.DiscardUnknown(m)
}

var xxx_messageInfo_AssignedSurvey proto.InternalMessageInfo

func (m *AssignedSurvey) GetSurveyKey() string {
	if m != nil {
		return m.SurveyKey
	}
	return ""
}

func (m *AssignedSurvey) GetValidFrom() int64 {
	if m != nil {
		return m.ValidFrom
	}
	return 0
}

func (m *AssignedSurvey) GetValidUntil() int64 {
	if m != nil {
		return m.ValidUntil
	}
	return 0
}

func (m *AssignedSurvey) GetStudyKey() string {
	if m != nil {
		return m.StudyKey
	}
	return ""
}

type AssignedSurveys struct {
	Surveys              []*AssignedSurvey `protobuf:"bytes,1,rep,name=surveys,proto3" json:"surveys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AssignedSurveys) Reset()         { *m = AssignedSurveys{} }
func (m *AssignedSurveys) String() string { return proto.CompactTextString(m) }
func (*AssignedSurveys) ProtoMessage()    {}
func (*AssignedSurveys) Descriptor() ([]byte, []int) {
	return fileDescriptor_b59e246e4c4c09f0, []int{2}
}

func (m *AssignedSurveys) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssignedSurveys.Unmarshal(m, b)
}
func (m *AssignedSurveys) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssignedSurveys.Marshal(b, m, deterministic)
}
func (m *AssignedSurveys) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssignedSurveys.Merge(m, src)
}
func (m *AssignedSurveys) XXX_Size() int {
	return xxx_messageInfo_AssignedSurveys.Size(m)
}
func (m *AssignedSurveys) XXX_DiscardUnknown() {
	xxx_messageInfo_AssignedSurveys.DiscardUnknown(m)
}

var xxx_messageInfo_AssignedSurveys proto.InternalMessageInfo

func (m *AssignedSurveys) GetSurveys() []*AssignedSurvey {
	if m != nil {
		return m.Surveys
	}
	return nil
}

func init() {
	proto.RegisterType((*Study)(nil), "inf.study.Study")
	proto.RegisterType((*Study_Props)(nil), "inf.study.Study.Props")
	proto.RegisterType((*Study_Configs)(nil), "inf.study.Study.Configs")
	proto.RegisterType((*AssignedSurvey)(nil), "inf.study.AssignedSurvey")
	proto.RegisterType((*AssignedSurveys)(nil), "inf.study.AssignedSurveys")
}

func init() {
	proto.RegisterFile("study.proto", fileDescriptor_b59e246e4c4c09f0)
}

var fileDescriptor_b59e246e4c4c09f0 = []byte{
	// 335 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x52, 0xc1, 0x4a, 0xc3, 0x40,
	0x14, 0x24, 0x49, 0x63, 0xcd, 0x0b, 0x54, 0xd9, 0x83, 0xc4, 0x16, 0x31, 0xf4, 0xd4, 0x83, 0x04,
	0x6c, 0xaf, 0x5e, 0x54, 0x2c, 0x42, 0x41, 0x64, 0x8b, 0x17, 0x2f, 0x25, 0x76, 0xb7, 0x65, 0xb1,
	0xd9, 0x5d, 0x76, 0x93, 0x62, 0xfe, 0xc1, 0x6f, 0xf0, 0x5b, 0xa5, 0x6f, 0x9b, 0xda, 0xe0, 0x6d,
	0x99, 0x99, 0x37, 0x6f, 0xde, 0xb0, 0x10, 0xdb, 0xb2, 0x62, 0x75, 0xa6, 0x8d, 0x2a, 0x15, 0x89,
	0x84, 0x5c, 0x65, 0x08, 0xf4, 0xcf, 0xf9, 0x97, 0x36, 0xdc, 0x5a, 0xa1, 0xa4, 0x23, 0x87, 0x3f,
	0x3e, 0x84, 0xf3, 0x1d, 0x47, 0x7a, 0xe0, 0x0b, 0x96, 0x78, 0xa9, 0x37, 0x8a, 0xa8, 0x2f, 0x18,
	0x19, 0x40, 0x84, 0x43, 0x8b, 0x4f, 0x5e, 0x27, 0x3e, 0xc2, 0xa7, 0x08, 0xcc, 0x78, 0x4d, 0x6e,
	0x20, 0xd4, 0x46, 0x69, 0x9b, 0x04, 0xa9, 0x37, 0x8a, 0xc7, 0x17, 0xd9, 0x61, 0x47, 0x86, 0x6e,
	0xd9, 0xeb, 0x8e, 0xa5, 0x4e, 0x44, 0xc6, 0xd0, 0x5d, 0x2a, 0xb9, 0x12, 0x6b, 0x9b, 0x74, 0x50,
	0x9f, 0xfc, 0xd3, 0x3f, 0x3a, 0x9e, 0x36, 0xc2, 0xfe, 0x33, 0x84, 0xe8, 0x41, 0xae, 0x00, 0x5c,
	0x0e, 0x99, 0x17, 0x1c, 0xf7, 0x45, 0xd4, 0x25, 0x7b, 0xc9, 0x0b, 0x4e, 0x52, 0x88, 0x19, 0xb7,
	0x4b, 0x23, 0x74, 0x29, 0x94, 0x44, 0xff, 0x88, 0x1e, 0x43, 0xfd, 0x3b, 0xe8, 0xee, 0xdd, 0xc9,
	0x2d, 0x84, 0xa6, 0xda, 0x70, 0x9b, 0x78, 0x69, 0x30, 0x8a, 0xc7, 0x03, 0x8c, 0xf1, 0xd7, 0x89,
	0xcd, 0x9e, 0x0e, 0x6f, 0xea, 0x94, 0xc3, 0x6f, 0x0f, 0x7a, 0xf7, 0xd6, 0x8a, 0xb5, 0xe4, 0x6c,
	0x5e, 0x99, 0x2d, 0xaf, 0x31, 0x11, 0xbe, 0xb0, 0x1a, 0x6f, 0x9f, 0x08, 0x91, 0x99, 0xa3, 0xb7,
	0xf9, 0x46, 0xb0, 0xc5, 0xca, 0xa8, 0x02, 0x9b, 0x0b, 0x68, 0x84, 0xc8, 0xd4, 0xa8, 0x82, 0x5c,
	0x43, 0xec, 0xe8, 0x4a, 0x96, 0x62, 0x83, 0x07, 0x05, 0xd4, 0x4d, 0xbc, 0xed, 0x90, 0x76, 0xf1,
	0x9d, 0x76, 0xf1, 0xc3, 0x29, 0x9c, 0xb5, 0xd3, 0x58, 0x32, 0x81, 0xae, 0x5b, 0xde, 0x9c, 0x75,
	0x79, 0xd4, 0x6e, 0x5b, 0x4c, 0x1b, 0xe5, 0x43, 0xf8, 0x1e, 0xe4, 0x5a, 0x7c, 0x9c, 0xe0, 0x2f,
	0x98, 0xfc, 0x06, 0x00, 0x00, 0xff, 0xff, 0x8c, 0x47, 0xbb, 0xae, 0x31, 0x02, 0x00, 0x00,
}
