// Code generated by protoc-gen-go. DO NOT EDIT.
// source: survey.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SurveyVersion struct {
	Published            int64       `protobuf:"varint,1,opt,name=published,proto3" json:"published,omitempty"`
	Unpublished          int64       `protobuf:"varint,2,opt,name=unpublished,proto3" json:"unpublished,omitempty"`
	SurveyDefinition     *SurveyItem `protobuf:"bytes,3,opt,name=survey_definition,json=surveyDefinition,proto3" json:"survey_definition,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SurveyVersion) Reset()         { *m = SurveyVersion{} }
func (m *SurveyVersion) String() string { return proto.CompactTextString(m) }
func (*SurveyVersion) ProtoMessage()    {}
func (*SurveyVersion) Descriptor() ([]byte, []int) {
	return fileDescriptor_a40f94eaa8e6ca46, []int{0}
}

func (m *SurveyVersion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SurveyVersion.Unmarshal(m, b)
}
func (m *SurveyVersion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SurveyVersion.Marshal(b, m, deterministic)
}
func (m *SurveyVersion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SurveyVersion.Merge(m, src)
}
func (m *SurveyVersion) XXX_Size() int {
	return xxx_messageInfo_SurveyVersion.Size(m)
}
func (m *SurveyVersion) XXX_DiscardUnknown() {
	xxx_messageInfo_SurveyVersion.DiscardUnknown(m)
}

var xxx_messageInfo_SurveyVersion proto.InternalMessageInfo

func (m *SurveyVersion) GetPublished() int64 {
	if m != nil {
		return m.Published
	}
	return 0
}

func (m *SurveyVersion) GetUnpublished() int64 {
	if m != nil {
		return m.Unpublished
	}
	return 0
}

func (m *SurveyVersion) GetSurveyDefinition() *SurveyItem {
	if m != nil {
		return m.SurveyDefinition
	}
	return nil
}

type SurveyItem struct {
	Id          string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Key         string      `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Follows     []string    `protobuf:"bytes,3,rep,name=follows,proto3" json:"follows,omitempty"`
	Condition   *Expression `protobuf:"bytes,4,opt,name=condition,proto3" json:"condition,omitempty"`
	Priority    float32     `protobuf:"fixed32,5,opt,name=priority,proto3" json:"priority,omitempty"`
	Version     int32       `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	VersionTags []string    `protobuf:"bytes,7,rep,name=version_tags,json=versionTags,proto3" json:"version_tags,omitempty"`
	// Question group attributes ->
	Items           []*SurveyItem `protobuf:"bytes,8,rep,name=items,proto3" json:"items,omitempty"`
	SelectionMethod *Expression   `protobuf:"bytes,9,opt,name=selection_method,json=selectionMethod,proto3" json:"selection_method,omitempty"`
	// Question attributes ->
	Type                 string           `protobuf:"bytes,10,opt,name=type,proto3" json:"type,omitempty"`
	Components           []*ItemComponent `protobuf:"bytes,11,rep,name=components,proto3" json:"components,omitempty"`
	Validations          []*Validation    `protobuf:"bytes,12,rep,name=validations,proto3" json:"validations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SurveyItem) Reset()         { *m = SurveyItem{} }
func (m *SurveyItem) String() string { return proto.CompactTextString(m) }
func (*SurveyItem) ProtoMessage()    {}
func (*SurveyItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_a40f94eaa8e6ca46, []int{1}
}

func (m *SurveyItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SurveyItem.Unmarshal(m, b)
}
func (m *SurveyItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SurveyItem.Marshal(b, m, deterministic)
}
func (m *SurveyItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SurveyItem.Merge(m, src)
}
func (m *SurveyItem) XXX_Size() int {
	return xxx_messageInfo_SurveyItem.Size(m)
}
func (m *SurveyItem) XXX_DiscardUnknown() {
	xxx_messageInfo_SurveyItem.DiscardUnknown(m)
}

var xxx_messageInfo_SurveyItem proto.InternalMessageInfo

func (m *SurveyItem) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SurveyItem) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SurveyItem) GetFollows() []string {
	if m != nil {
		return m.Follows
	}
	return nil
}

func (m *SurveyItem) GetCondition() *Expression {
	if m != nil {
		return m.Condition
	}
	return nil
}

func (m *SurveyItem) GetPriority() float32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *SurveyItem) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *SurveyItem) GetVersionTags() []string {
	if m != nil {
		return m.VersionTags
	}
	return nil
}

func (m *SurveyItem) GetItems() []*SurveyItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *SurveyItem) GetSelectionMethod() *Expression {
	if m != nil {
		return m.SelectionMethod
	}
	return nil
}

func (m *SurveyItem) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *SurveyItem) GetComponents() []*ItemComponent {
	if m != nil {
		return m.Components
	}
	return nil
}

func (m *SurveyItem) GetValidations() []*Validation {
	if m != nil {
		return m.Validations
	}
	return nil
}

type Expression struct {
	Name                 string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ReturnType           string           `protobuf:"bytes,2,opt,name=returnType,proto3" json:"returnType,omitempty"`
	Data                 []*ExpressionArg `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Expression) Reset()         { *m = Expression{} }
func (m *Expression) String() string { return proto.CompactTextString(m) }
func (*Expression) ProtoMessage()    {}
func (*Expression) Descriptor() ([]byte, []int) {
	return fileDescriptor_a40f94eaa8e6ca46, []int{2}
}

func (m *Expression) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Expression.Unmarshal(m, b)
}
func (m *Expression) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Expression.Marshal(b, m, deterministic)
}
func (m *Expression) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Expression.Merge(m, src)
}
func (m *Expression) XXX_Size() int {
	return xxx_messageInfo_Expression.Size(m)
}
func (m *Expression) XXX_DiscardUnknown() {
	xxx_messageInfo_Expression.DiscardUnknown(m)
}

var xxx_messageInfo_Expression proto.InternalMessageInfo

func (m *Expression) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Expression) GetReturnType() string {
	if m != nil {
		return m.ReturnType
	}
	return ""
}

func (m *Expression) GetData() []*ExpressionArg {
	if m != nil {
		return m.Data
	}
	return nil
}

type ExpressionArg struct {
	Dtype string `protobuf:"bytes,1,opt,name=dtype,proto3" json:"dtype,omitempty"`
	// Types that are valid to be assigned to Data:
	//	*ExpressionArg_Exp
	//	*ExpressionArg_Str
	//	*ExpressionArg_Num
	Data                 isExpressionArg_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ExpressionArg) Reset()         { *m = ExpressionArg{} }
func (m *ExpressionArg) String() string { return proto.CompactTextString(m) }
func (*ExpressionArg) ProtoMessage()    {}
func (*ExpressionArg) Descriptor() ([]byte, []int) {
	return fileDescriptor_a40f94eaa8e6ca46, []int{3}
}

func (m *ExpressionArg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExpressionArg.Unmarshal(m, b)
}
func (m *ExpressionArg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExpressionArg.Marshal(b, m, deterministic)
}
func (m *ExpressionArg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExpressionArg.Merge(m, src)
}
func (m *ExpressionArg) XXX_Size() int {
	return xxx_messageInfo_ExpressionArg.Size(m)
}
func (m *ExpressionArg) XXX_DiscardUnknown() {
	xxx_messageInfo_ExpressionArg.DiscardUnknown(m)
}

var xxx_messageInfo_ExpressionArg proto.InternalMessageInfo

func (m *ExpressionArg) GetDtype() string {
	if m != nil {
		return m.Dtype
	}
	return ""
}

type isExpressionArg_Data interface {
	isExpressionArg_Data()
}

type ExpressionArg_Exp struct {
	Exp *Expression `protobuf:"bytes,2,opt,name=exp,proto3,oneof"`
}

type ExpressionArg_Str struct {
	Str string `protobuf:"bytes,3,opt,name=str,proto3,oneof"`
}

type ExpressionArg_Num struct {
	Num float64 `protobuf:"fixed64,4,opt,name=num,proto3,oneof"`
}

func (*ExpressionArg_Exp) isExpressionArg_Data() {}

func (*ExpressionArg_Str) isExpressionArg_Data() {}

func (*ExpressionArg_Num) isExpressionArg_Data() {}

func (m *ExpressionArg) GetData() isExpressionArg_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ExpressionArg) GetExp() *Expression {
	if x, ok := m.GetData().(*ExpressionArg_Exp); ok {
		return x.Exp
	}
	return nil
}

func (m *ExpressionArg) GetStr() string {
	if x, ok := m.GetData().(*ExpressionArg_Str); ok {
		return x.Str
	}
	return ""
}

func (m *ExpressionArg) GetNum() float64 {
	if x, ok := m.GetData().(*ExpressionArg_Num); ok {
		return x.Num
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ExpressionArg) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ExpressionArg_Exp)(nil),
		(*ExpressionArg_Str)(nil),
		(*ExpressionArg_Num)(nil),
	}
}

type Validation struct {
	Key                  string      `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Type                 string      `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Rule                 *Expression `protobuf:"bytes,3,opt,name=rule,proto3" json:"rule,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Validation) Reset()         { *m = Validation{} }
func (m *Validation) String() string { return proto.CompactTextString(m) }
func (*Validation) ProtoMessage()    {}
func (*Validation) Descriptor() ([]byte, []int) {
	return fileDescriptor_a40f94eaa8e6ca46, []int{4}
}

func (m *Validation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Validation.Unmarshal(m, b)
}
func (m *Validation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Validation.Marshal(b, m, deterministic)
}
func (m *Validation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Validation.Merge(m, src)
}
func (m *Validation) XXX_Size() int {
	return xxx_messageInfo_Validation.Size(m)
}
func (m *Validation) XXX_DiscardUnknown() {
	xxx_messageInfo_Validation.DiscardUnknown(m)
}

var xxx_messageInfo_Validation proto.InternalMessageInfo

func (m *Validation) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Validation) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Validation) GetRule() *Expression {
	if m != nil {
		return m.Rule
	}
	return nil
}

type ItemComponent struct {
	Role             string             `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Key              string             `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Content          []*LocalisedObject `protobuf:"bytes,3,rep,name=content,proto3" json:"content,omitempty"`
	DisplayCondition *Expression        `protobuf:"bytes,4,opt,name=display_condition,json=displayCondition,proto3" json:"display_condition,omitempty"`
	Disabled         *Expression        `protobuf:"bytes,5,opt,name=disabled,proto3" json:"disabled,omitempty"`
	// group component
	Items []*ItemComponent `protobuf:"bytes,6,rep,name=items,proto3" json:"items,omitempty"`
	Order *Expression      `protobuf:"bytes,7,opt,name=order,proto3" json:"order,omitempty"`
	// response compontent
	Dtype                string   `protobuf:"bytes,8,opt,name=dtype,proto3" json:"dtype,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemComponent) Reset()         { *m = ItemComponent{} }
func (m *ItemComponent) String() string { return proto.CompactTextString(m) }
func (*ItemComponent) ProtoMessage()    {}
func (*ItemComponent) Descriptor() ([]byte, []int) {
	return fileDescriptor_a40f94eaa8e6ca46, []int{5}
}

func (m *ItemComponent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemComponent.Unmarshal(m, b)
}
func (m *ItemComponent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemComponent.Marshal(b, m, deterministic)
}
func (m *ItemComponent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemComponent.Merge(m, src)
}
func (m *ItemComponent) XXX_Size() int {
	return xxx_messageInfo_ItemComponent.Size(m)
}
func (m *ItemComponent) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemComponent.DiscardUnknown(m)
}

var xxx_messageInfo_ItemComponent proto.InternalMessageInfo

func (m *ItemComponent) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *ItemComponent) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ItemComponent) GetContent() []*LocalisedObject {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *ItemComponent) GetDisplayCondition() *Expression {
	if m != nil {
		return m.DisplayCondition
	}
	return nil
}

func (m *ItemComponent) GetDisabled() *Expression {
	if m != nil {
		return m.Disabled
	}
	return nil
}

func (m *ItemComponent) GetItems() []*ItemComponent {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ItemComponent) GetOrder() *Expression {
	if m != nil {
		return m.Order
	}
	return nil
}

func (m *ItemComponent) GetDtype() string {
	if m != nil {
		return m.Dtype
	}
	return ""
}

type LocalisedObject struct {
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// for texts:
	Parts                []*ExpressionArg `protobuf:"bytes,2,rep,name=parts,proto3" json:"parts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *LocalisedObject) Reset()         { *m = LocalisedObject{} }
func (m *LocalisedObject) String() string { return proto.CompactTextString(m) }
func (*LocalisedObject) ProtoMessage()    {}
func (*LocalisedObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_a40f94eaa8e6ca46, []int{6}
}

func (m *LocalisedObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocalisedObject.Unmarshal(m, b)
}
func (m *LocalisedObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocalisedObject.Marshal(b, m, deterministic)
}
func (m *LocalisedObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocalisedObject.Merge(m, src)
}
func (m *LocalisedObject) XXX_Size() int {
	return xxx_messageInfo_LocalisedObject.Size(m)
}
func (m *LocalisedObject) XXX_DiscardUnknown() {
	xxx_messageInfo_LocalisedObject.DiscardUnknown(m)
}

var xxx_messageInfo_LocalisedObject proto.InternalMessageInfo

func (m *LocalisedObject) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *LocalisedObject) GetParts() []*ExpressionArg {
	if m != nil {
		return m.Parts
	}
	return nil
}

func init() {
	proto.RegisterType((*SurveyVersion)(nil), "inf.survey.SurveyVersion")
	proto.RegisterType((*SurveyItem)(nil), "inf.survey.SurveyItem")
	proto.RegisterType((*Expression)(nil), "inf.survey.Expression")
	proto.RegisterType((*ExpressionArg)(nil), "inf.survey.ExpressionArg")
	proto.RegisterType((*Validation)(nil), "inf.survey.Validation")
	proto.RegisterType((*ItemComponent)(nil), "inf.survey.ItemComponent")
	proto.RegisterType((*LocalisedObject)(nil), "inf.survey.LocalisedObject")
}

func init() { proto.RegisterFile("survey.proto", fileDescriptor_a40f94eaa8e6ca46) }

var fileDescriptor_a40f94eaa8e6ca46 = []byte{
	// 630 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x4b, 0x6f, 0xd4, 0x3c,
	0x14, 0xfd, 0x92, 0xcc, 0x2b, 0x77, 0xda, 0xaf, 0x83, 0x85, 0x90, 0x79, 0x08, 0x85, 0xac, 0x46,
	0x55, 0x19, 0xa4, 0x02, 0x12, 0x2c, 0xdb, 0x82, 0x04, 0x12, 0x08, 0x29, 0x54, 0x5d, 0xb0, 0x60,
	0x94, 0x89, 0xdd, 0xd6, 0x90, 0xd8, 0x91, 0xed, 0x94, 0xce, 0x92, 0xff, 0xc0, 0x1f, 0x63, 0xcb,
	0xaf, 0x41, 0xb6, 0x27, 0x8f, 0xbe, 0xa6, 0xec, 0xae, 0x8f, 0x4f, 0xee, 0x3d, 0x3e, 0xf7, 0xde,
	0xc0, 0x86, 0xaa, 0xe4, 0x19, 0x5d, 0xce, 0x4a, 0x29, 0xb4, 0x40, 0xc0, 0xf8, 0xf1, 0xcc, 0x21,
	0xf1, 0x2f, 0x0f, 0x36, 0x3f, 0xdb, 0xf0, 0x88, 0x4a, 0xc5, 0x04, 0x47, 0x8f, 0x20, 0x2c, 0xab,
	0x45, 0xce, 0xd4, 0x29, 0x25, 0xd8, 0x8b, 0xbc, 0x69, 0x90, 0xb4, 0x00, 0x8a, 0x60, 0x5c, 0xf1,
	0xf6, 0xde, 0xb7, 0xf7, 0x5d, 0x08, 0x1d, 0xc0, 0x1d, 0x97, 0x7b, 0x4e, 0xe8, 0x31, 0xe3, 0x4c,
	0x33, 0xc1, 0x71, 0x10, 0x79, 0xd3, 0xf1, 0xee, 0xbd, 0x59, 0x5b, 0x79, 0xe6, 0xaa, 0xbe, 0xd7,
	0xb4, 0x48, 0x26, 0x0e, 0x7a, 0xd3, 0xf0, 0xe3, 0xdf, 0x01, 0x40, 0x4b, 0x40, 0xff, 0x83, 0xcf,
	0x9c, 0x98, 0x30, 0xf1, 0x19, 0x41, 0x13, 0x08, 0xbe, 0xd3, 0xa5, 0xad, 0x1e, 0x26, 0x26, 0x44,
	0x18, 0x86, 0xc7, 0x22, 0xcf, 0xc5, 0x0f, 0x85, 0x83, 0x28, 0x98, 0x86, 0x49, 0x7d, 0x44, 0x2f,
	0x20, 0xcc, 0x04, 0x27, 0x4e, 0x47, 0xef, 0xaa, 0x8e, 0xb7, 0xe7, 0xa5, 0xa4, 0xca, 0x3c, 0x3d,
	0x69, 0x89, 0xe8, 0x01, 0x8c, 0x4a, 0xc9, 0x84, 0x64, 0x7a, 0x89, 0xfb, 0x91, 0x37, 0xf5, 0x93,
	0xe6, 0x6c, 0x6a, 0x9d, 0x39, 0xb3, 0xf0, 0x20, 0xf2, 0xa6, 0xfd, 0xa4, 0x3e, 0xa2, 0x27, 0xb0,
	0xb1, 0x0a, 0xe7, 0x3a, 0x3d, 0x51, 0x78, 0x68, 0xa5, 0x8c, 0x57, 0xd8, 0x61, 0x7a, 0xa2, 0xd0,
	0x0e, 0xf4, 0x99, 0xa6, 0x85, 0xc2, 0xa3, 0x28, 0x58, 0x63, 0x89, 0x23, 0xa1, 0x3d, 0x98, 0x28,
	0x9a, 0xd3, 0xcc, 0x68, 0x9a, 0x17, 0x54, 0x9f, 0x0a, 0x82, 0xc3, 0xb5, 0x6f, 0xd8, 0x6a, 0xf8,
	0x1f, 0x2d, 0x1d, 0x21, 0xe8, 0xe9, 0x65, 0x49, 0x31, 0x58, 0xb3, 0x6c, 0x8c, 0x5e, 0x03, 0x64,
	0xa2, 0x28, 0x05, 0xa7, 0x5c, 0x2b, 0x3c, 0xb6, 0x4a, 0xee, 0x77, 0x13, 0x1a, 0x0d, 0x07, 0x35,
	0x23, 0xe9, 0x90, 0xd1, 0x2b, 0x18, 0x9f, 0xa5, 0x39, 0x23, 0xa9, 0x29, 0xa1, 0xf0, 0xc6, 0xd5,
	0x57, 0x1c, 0x35, 0xd7, 0x49, 0x97, 0x1a, 0x0b, 0x80, 0x56, 0xa7, 0x91, 0xc5, 0xd3, 0x82, 0xae,
	0x9a, 0x6a, 0x63, 0xf4, 0x18, 0x40, 0x52, 0x5d, 0x49, 0x7e, 0x68, 0x04, 0xbb, 0xee, 0x76, 0x10,
	0xf4, 0x14, 0x7a, 0x24, 0xd5, 0xa9, 0xed, 0xf0, 0x25, 0xc1, 0x6d, 0xe6, 0x3d, 0x79, 0x92, 0x58,
	0x5a, 0xfc, 0xd3, 0x83, 0xcd, 0x0b, 0x38, 0xba, 0x0b, 0x7d, 0x62, 0xcd, 0x70, 0x55, 0xdd, 0x01,
	0x6d, 0x43, 0x40, 0xcf, 0x4b, 0x5b, 0xef, 0x46, 0x5f, 0xdf, 0xfd, 0x97, 0x18, 0x12, 0x42, 0x10,
	0x28, 0x2d, 0xed, 0x3c, 0x87, 0x06, 0x53, 0x5a, 0x1a, 0x8c, 0x57, 0x85, 0x9d, 0x2d, 0xcf, 0x60,
	0xbc, 0x2a, 0xf6, 0x07, 0x4e, 0x6a, 0xfc, 0x15, 0xa0, 0xf5, 0xa3, 0x9e, 0x5b, 0xaf, 0x9d, 0xdb,
	0xba, 0x3b, 0x7e, 0xa7, 0x3b, 0xdb, 0xd0, 0x93, 0x55, 0x4e, 0xaf, 0x5b, 0x9a, 0x4e, 0xa3, 0x2d,
	0x27, 0xfe, 0xe3, 0xc3, 0xe6, 0x85, 0x66, 0x99, 0x8c, 0x52, 0xe4, 0x8d, 0xb1, 0x26, 0xbe, 0x66,
	0x5f, 0x5e, 0xc2, 0x30, 0x13, 0x5c, 0x53, 0xae, 0x57, 0x6e, 0x3e, 0xec, 0x96, 0xf9, 0x20, 0xb2,
	0x34, 0x67, 0x8a, 0x92, 0x4f, 0x8b, 0x6f, 0x34, 0xd3, 0x49, 0xcd, 0x35, 0xcb, 0x4d, 0x98, 0x2a,
	0xf3, 0x74, 0x39, 0xff, 0xd7, 0xa5, 0x9a, 0xac, 0x3e, 0x38, 0x68, 0x76, 0x6b, 0x17, 0x46, 0x84,
	0xa9, 0x74, 0x91, 0x53, 0x62, 0x77, 0xeb, 0xe6, 0x6f, 0x1b, 0x1e, 0x7a, 0x56, 0xaf, 0xcd, 0xe0,
	0xb6, 0x61, 0x5d, 0x6d, 0xce, 0x0e, 0xf4, 0x85, 0x24, 0x54, 0xe2, 0xe1, 0xda, 0x0a, 0x8e, 0xd4,
	0x0e, 0xc6, 0xa8, 0x33, 0x18, 0xf1, 0x11, 0x6c, 0x5d, 0x72, 0xc2, 0xb8, 0x9b, 0x09, 0xd2, 0xb8,
	0x6b, 0x62, 0xa3, 0xad, 0x4c, 0xa5, 0x56, 0xd8, 0xbf, 0x6d, 0x2e, 0x1d, 0x6f, 0xbf, 0xff, 0x25,
	0x48, 0x4b, 0xb6, 0x18, 0xd8, 0xdf, 0xf1, 0xf3, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x60, 0x21,
	0xee, 0xf6, 0x9e, 0x05, 0x00, 0x00,
}
