// Code generated by protoc-gen-go. DO NOT EDIT.
// source: survey.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SurveyVersion struct {
	Published            int64       `protobuf:"varint,1,opt,name=published,proto3" json:"published,omitempty"`
	Unpublished          int64       `protobuf:"varint,2,opt,name=unpublished,proto3" json:"unpublished,omitempty"`
	SurveyDefinition     *SurveyItem `protobuf:"bytes,3,opt,name=surveyDefinition,proto3" json:"surveyDefinition,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SurveyVersion) Reset()         { *m = SurveyVersion{} }
func (m *SurveyVersion) String() string { return proto.CompactTextString(m) }
func (*SurveyVersion) ProtoMessage()    {}
func (*SurveyVersion) Descriptor() ([]byte, []int) {
	return fileDescriptor_a40f94eaa8e6ca46, []int{0}
}

func (m *SurveyVersion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SurveyVersion.Unmarshal(m, b)
}
func (m *SurveyVersion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SurveyVersion.Marshal(b, m, deterministic)
}
func (m *SurveyVersion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SurveyVersion.Merge(m, src)
}
func (m *SurveyVersion) XXX_Size() int {
	return xxx_messageInfo_SurveyVersion.Size(m)
}
func (m *SurveyVersion) XXX_DiscardUnknown() {
	xxx_messageInfo_SurveyVersion.DiscardUnknown(m)
}

var xxx_messageInfo_SurveyVersion proto.InternalMessageInfo

func (m *SurveyVersion) GetPublished() int64 {
	if m != nil {
		return m.Published
	}
	return 0
}

func (m *SurveyVersion) GetUnpublished() int64 {
	if m != nil {
		return m.Unpublished
	}
	return 0
}

func (m *SurveyVersion) GetSurveyDefinition() *SurveyItem {
	if m != nil {
		return m.SurveyDefinition
	}
	return nil
}

type SurveyItem struct {
	Id          string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Key         string      `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Follows     []string    `protobuf:"bytes,3,rep,name=follows,proto3" json:"follows,omitempty"`
	Condition   *Expression `protobuf:"bytes,4,opt,name=condition,proto3" json:"condition,omitempty"`
	Priority    float32     `protobuf:"fixed32,5,opt,name=priority,proto3" json:"priority,omitempty"`
	Version     int32       `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	VersionTags []string    `protobuf:"bytes,7,rep,name=versionTags,proto3" json:"versionTags,omitempty"`
	// Question group attributes ->
	Items           []*SurveyItem `protobuf:"bytes,8,rep,name=items,proto3" json:"items,omitempty"`
	SelectionMethod *Expression   `protobuf:"bytes,9,opt,name=selectionMethod,proto3" json:"selectionMethod,omitempty"`
	// Question attributes ->
	Type                 string   `protobuf:"bytes,10,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SurveyItem) Reset()         { *m = SurveyItem{} }
func (m *SurveyItem) String() string { return proto.CompactTextString(m) }
func (*SurveyItem) ProtoMessage()    {}
func (*SurveyItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_a40f94eaa8e6ca46, []int{1}
}

func (m *SurveyItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SurveyItem.Unmarshal(m, b)
}
func (m *SurveyItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SurveyItem.Marshal(b, m, deterministic)
}
func (m *SurveyItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SurveyItem.Merge(m, src)
}
func (m *SurveyItem) XXX_Size() int {
	return xxx_messageInfo_SurveyItem.Size(m)
}
func (m *SurveyItem) XXX_DiscardUnknown() {
	xxx_messageInfo_SurveyItem.DiscardUnknown(m)
}

var xxx_messageInfo_SurveyItem proto.InternalMessageInfo

func (m *SurveyItem) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SurveyItem) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SurveyItem) GetFollows() []string {
	if m != nil {
		return m.Follows
	}
	return nil
}

func (m *SurveyItem) GetCondition() *Expression {
	if m != nil {
		return m.Condition
	}
	return nil
}

func (m *SurveyItem) GetPriority() float32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *SurveyItem) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *SurveyItem) GetVersionTags() []string {
	if m != nil {
		return m.VersionTags
	}
	return nil
}

func (m *SurveyItem) GetItems() []*SurveyItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *SurveyItem) GetSelectionMethod() *Expression {
	if m != nil {
		return m.SelectionMethod
	}
	return nil
}

func (m *SurveyItem) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type Expression struct {
	Name                 string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Dtype                string           `protobuf:"bytes,2,opt,name=dtype,proto3" json:"dtype,omitempty"`
	Data                 []*ExpressionArg `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Expression) Reset()         { *m = Expression{} }
func (m *Expression) String() string { return proto.CompactTextString(m) }
func (*Expression) ProtoMessage()    {}
func (*Expression) Descriptor() ([]byte, []int) {
	return fileDescriptor_a40f94eaa8e6ca46, []int{2}
}

func (m *Expression) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Expression.Unmarshal(m, b)
}
func (m *Expression) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Expression.Marshal(b, m, deterministic)
}
func (m *Expression) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Expression.Merge(m, src)
}
func (m *Expression) XXX_Size() int {
	return xxx_messageInfo_Expression.Size(m)
}
func (m *Expression) XXX_DiscardUnknown() {
	xxx_messageInfo_Expression.DiscardUnknown(m)
}

var xxx_messageInfo_Expression proto.InternalMessageInfo

func (m *Expression) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Expression) GetDtype() string {
	if m != nil {
		return m.Dtype
	}
	return ""
}

func (m *Expression) GetData() []*ExpressionArg {
	if m != nil {
		return m.Data
	}
	return nil
}

type ExpressionArg struct {
	// Types that are valid to be assigned to Data:
	//	*ExpressionArg_Exp
	//	*ExpressionArg_Str
	//	*ExpressionArg_Num
	Data                 isExpressionArg_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ExpressionArg) Reset()         { *m = ExpressionArg{} }
func (m *ExpressionArg) String() string { return proto.CompactTextString(m) }
func (*ExpressionArg) ProtoMessage()    {}
func (*ExpressionArg) Descriptor() ([]byte, []int) {
	return fileDescriptor_a40f94eaa8e6ca46, []int{3}
}

func (m *ExpressionArg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExpressionArg.Unmarshal(m, b)
}
func (m *ExpressionArg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExpressionArg.Marshal(b, m, deterministic)
}
func (m *ExpressionArg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExpressionArg.Merge(m, src)
}
func (m *ExpressionArg) XXX_Size() int {
	return xxx_messageInfo_ExpressionArg.Size(m)
}
func (m *ExpressionArg) XXX_DiscardUnknown() {
	xxx_messageInfo_ExpressionArg.DiscardUnknown(m)
}

var xxx_messageInfo_ExpressionArg proto.InternalMessageInfo

type isExpressionArg_Data interface {
	isExpressionArg_Data()
}

type ExpressionArg_Exp struct {
	Exp *Expression `protobuf:"bytes,1,opt,name=exp,proto3,oneof"`
}

type ExpressionArg_Str struct {
	Str string `protobuf:"bytes,2,opt,name=str,proto3,oneof"`
}

type ExpressionArg_Num struct {
	Num float64 `protobuf:"fixed64,3,opt,name=num,proto3,oneof"`
}

func (*ExpressionArg_Exp) isExpressionArg_Data() {}

func (*ExpressionArg_Str) isExpressionArg_Data() {}

func (*ExpressionArg_Num) isExpressionArg_Data() {}

func (m *ExpressionArg) GetData() isExpressionArg_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ExpressionArg) GetExp() *Expression {
	if x, ok := m.GetData().(*ExpressionArg_Exp); ok {
		return x.Exp
	}
	return nil
}

func (m *ExpressionArg) GetStr() string {
	if x, ok := m.GetData().(*ExpressionArg_Str); ok {
		return x.Str
	}
	return ""
}

func (m *ExpressionArg) GetNum() float64 {
	if x, ok := m.GetData().(*ExpressionArg_Num); ok {
		return x.Num
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ExpressionArg) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ExpressionArg_Exp)(nil),
		(*ExpressionArg_Str)(nil),
		(*ExpressionArg_Num)(nil),
	}
}

type ResponseItem struct {
	Key                  string          `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string          `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Items                []*ResponseItem `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Dtype                string          `protobuf:"bytes,4,opt,name=dtype,proto3" json:"dtype,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ResponseItem) Reset()         { *m = ResponseItem{} }
func (m *ResponseItem) String() string { return proto.CompactTextString(m) }
func (*ResponseItem) ProtoMessage()    {}
func (*ResponseItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_a40f94eaa8e6ca46, []int{4}
}

func (m *ResponseItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseItem.Unmarshal(m, b)
}
func (m *ResponseItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseItem.Marshal(b, m, deterministic)
}
func (m *ResponseItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseItem.Merge(m, src)
}
func (m *ResponseItem) XXX_Size() int {
	return xxx_messageInfo_ResponseItem.Size(m)
}
func (m *ResponseItem) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseItem.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseItem proto.InternalMessageInfo

func (m *ResponseItem) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ResponseItem) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *ResponseItem) GetItems() []*ResponseItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ResponseItem) GetDtype() string {
	if m != nil {
		return m.Dtype
	}
	return ""
}

func init() {
	proto.RegisterType((*SurveyVersion)(nil), "influenzanet.survey.SurveyVersion")
	proto.RegisterType((*SurveyItem)(nil), "influenzanet.survey.SurveyItem")
	proto.RegisterType((*Expression)(nil), "influenzanet.survey.Expression")
	proto.RegisterType((*ExpressionArg)(nil), "influenzanet.survey.ExpressionArg")
	proto.RegisterType((*ResponseItem)(nil), "influenzanet.survey.ResponseItem")
}

func init() { proto.RegisterFile("survey.proto", fileDescriptor_a40f94eaa8e6ca46) }

var fileDescriptor_a40f94eaa8e6ca46 = []byte{
	// 454 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0x41, 0x6f, 0xd4, 0x3c,
	0x10, 0x86, 0xbf, 0xc4, 0x9b, 0x6d, 0x33, 0xdb, 0x7e, 0x54, 0x43, 0x0f, 0x16, 0x42, 0x22, 0xe4,
	0x94, 0xd3, 0x1e, 0x5a, 0x01, 0x27, 0x0e, 0x54, 0x20, 0x51, 0x21, 0x2e, 0x06, 0x71, 0xe0, 0x96,
	0x36, 0xb3, 0xad, 0x45, 0x62, 0x47, 0xb6, 0xb3, 0x74, 0xb9, 0xf3, 0x2f, 0xf8, 0x9b, 0xdc, 0x91,
	0xed, 0xdd, 0xcd, 0x02, 0x15, 0xed, 0x6d, 0xe6, 0xf5, 0x4c, 0xfc, 0xcc, 0xeb, 0x09, 0x1c, 0xd8,
	0xc1, 0x2c, 0x69, 0x35, 0xef, 0x8d, 0x76, 0x1a, 0x1f, 0x4a, 0xb5, 0x68, 0x07, 0x52, 0xdf, 0x6a,
	0x45, 0x6e, 0x1e, 0x8f, 0xca, 0x1f, 0x09, 0x1c, 0x7e, 0x08, 0xe1, 0x27, 0x32, 0x56, 0x6a, 0x85,
	0x8f, 0x21, 0xef, 0x87, 0x8b, 0x56, 0xda, 0x6b, 0x6a, 0x78, 0x52, 0x24, 0x15, 0x13, 0xa3, 0x80,
	0x05, 0xcc, 0x06, 0x35, 0x9e, 0xa7, 0xe1, 0x7c, 0x57, 0xc2, 0x77, 0x70, 0x14, 0xbf, 0xfd, 0x9a,
	0x16, 0x52, 0x49, 0x27, 0xb5, 0xe2, 0xac, 0x48, 0xaa, 0xd9, 0xc9, 0x93, 0xf9, 0x2d, 0x04, 0xf3,
	0x78, 0xfb, 0xb9, 0xa3, 0x4e, 0xfc, 0xd5, 0x58, 0xfe, 0x4c, 0x01, 0xc6, 0x02, 0xfc, 0x1f, 0x52,
	0x19, 0xa1, 0x72, 0x91, 0xca, 0x06, 0x8f, 0x80, 0x7d, 0xa1, 0x55, 0xa0, 0xc8, 0x85, 0x0f, 0x91,
	0xc3, 0xde, 0x42, 0xb7, 0xad, 0xfe, 0x6a, 0x39, 0x2b, 0x58, 0x95, 0x8b, 0x4d, 0x8a, 0x2f, 0x21,
	0xbf, 0xd4, 0xaa, 0x89, 0x40, 0x93, 0x7f, 0x00, 0xbd, 0xb9, 0xe9, 0x0d, 0x59, 0xef, 0x85, 0x18,
	0x3b, 0xf0, 0x11, 0xec, 0xf7, 0x46, 0x6a, 0x23, 0xdd, 0x8a, 0x67, 0x45, 0x52, 0xa5, 0x62, 0x9b,
	0xfb, 0x4b, 0x97, 0xd1, 0x3d, 0x3e, 0x2d, 0x92, 0x2a, 0x13, 0x9b, 0xd4, 0xdb, 0xb5, 0x0e, 0x3f,
	0xd6, 0x57, 0x96, 0xef, 0x05, 0xa4, 0x5d, 0x09, 0x9f, 0x41, 0x26, 0x1d, 0x75, 0x96, 0xef, 0x17,
	0xec, 0x3e, 0x1e, 0xc5, 0x6a, 0x3c, 0x87, 0x07, 0x96, 0x5a, 0xba, 0xf4, 0x6c, 0xef, 0xc9, 0x5d,
	0xeb, 0x86, 0xe7, 0xf7, 0x9b, 0xe9, 0xcf, 0x3e, 0x44, 0x98, 0xb8, 0x55, 0x4f, 0x1c, 0x82, 0x8b,
	0x21, 0x2e, 0x15, 0xc0, 0xd8, 0xe2, 0x2b, 0x54, 0xdd, 0xd1, 0xda, 0xf8, 0x10, 0xe3, 0x31, 0x64,
	0x4d, 0x68, 0x8b, 0xe6, 0xc7, 0x04, 0x9f, 0xc3, 0xa4, 0xa9, 0x5d, 0x1d, 0xbc, 0x9f, 0x9d, 0x94,
	0x77, 0xb0, 0xbc, 0x32, 0x57, 0x22, 0xd4, 0x97, 0x0e, 0x0e, 0x7f, 0x93, 0xf1, 0x14, 0x18, 0xdd,
	0xf4, 0xe1, 0xc6, 0xbb, 0x67, 0x7a, 0xfb, 0x9f, 0xf0, 0xd5, 0x88, 0xc0, 0xac, 0x33, 0x91, 0xc8,
	0x6b, 0xd6, 0x19, 0xaf, 0xa9, 0xa1, 0x0b, 0x1b, 0x98, 0x78, 0x4d, 0x0d, 0xdd, 0xd9, 0x34, 0x52,
	0x96, 0xdf, 0x13, 0x38, 0x10, 0x64, 0x7b, 0xad, 0x2c, 0x85, 0xfd, 0x5a, 0xef, 0x53, 0x32, 0xee,
	0xd3, 0x31, 0x64, 0xcb, 0xba, 0x1d, 0xb6, 0x63, 0x86, 0x04, 0x5f, 0x6c, 0x1e, 0x2d, 0xce, 0xf9,
	0xf4, 0x56, 0xbe, 0xdd, 0x2f, 0x6f, 0x9e, 0x6d, 0xeb, 0xda, 0x64, 0xc7, 0xb5, 0xb3, 0xec, 0x33,
	0xab, 0x7b, 0x79, 0x31, 0x0d, 0xff, 0xe9, 0xe9, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x66, 0xc9,
	0x56, 0xae, 0xb7, 0x03, 0x00, 0x00,
}
